name: Build App

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/deploy_app.yml'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'
  AWS_S3_BUCKET_NAME: "millerd-origin"
  AWS_CLOUDFRONT_DISTRIBUTION_ID: "E2X93TEKFIITJQ"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: app/millerd/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: app/millerd
    - name: Build site
      run: npm run build
      working-directory: app/millerd
    - name: Deploy to AWS S3
      run: aws s3 sync ./dist/ s3://${{ env.AWS_S3_BUCKET_NAME }}
      working-directory: app/millerd
    - name: Create AWS Cloudfront Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
